wmibeat:
  # Defines how often an event is sent to the output
  period: 60s

  classes:
    - class: Win32_OperatingSystem
      fields:
      - FreePhysicalMemory
      - FreeSpaceInPagingFiles
      - FreeVirtualMemory
      - NumberOfProcesses
      - NumberOfUsers
    - class: Win32_PerfFormattedData_PerfDisk_LogicalDisk
      fields:
      - Name
      - FreeMegabytes
      - PercentFreeSpace
      - CurrentDiskQueueLength
      - DiskReadsPerSec
      - DiskWritesPerSec
      - DiskBytesPerSec
      - PercentDiskReadTime
      - PercentDiskWriteTime
      - PercentDiskTime
      whereclause: Name != "_Total"
      objecttitlecolumn: Name
    - class: Win32_PerfFormattedData_PerfOS_Memory
      fields:
      - CommittedBytes
      - AvailableBytes
      - PercentCommittedBytesInUse
    - class: CIM_OperatingSystem
      fields:
      - CSName
      - Name
      - Caption
      - installdate

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]
  hosts: ["172.30.1.48:5044"]  